meta:
    extract_upstream: False

tasks:

  - source: overview.py
    name: "overview"
    upstream: []
    product: 
      nb: "{{config_output}}/overview.html"
      data: "{{config_output}}/overview.xlsx"
    params:
      config_templates: "{{config_templates}}"
      config_root: "{{config_root}}"
      config_output: "{{config_output}}"
      path_output: "{{config_output}}/processed_{{fit_ne_peaks}}_{{match_mode}}_{{interpolator}}"
      keys: "{{dataset_key}}"
      resolution: True
    nbconvert_export_kwargs:
        # optionally hide the code from the report
        exclude_input: True    

  - source: spectraframe_load.py
    name: "spectraframe_[[key]]"
    upstream: []
    product: 
      nb: "{{config_output}}/[[key]]/spectraframe_load.{{report_format}}"
      h5: "{{config_output}}/[[key]]/spectraframe_load.h5"
      xlsx: "{{config_output}}/[[key]]/spectraframe_load.xlsx"
    params:
      config_templates: "{{config_templates}}"
      config_root: "{{config_root}}"
    grid:
      key: "{{dataset_key}}"


  - source: spectraframe_calibrate.py
    name: "spectracal_[[key]]"    
    product: 
      nb: "{{config_output}}/processed_{{fit_ne_peaks}}_{{match_mode}}_{{interpolator}}/[[key]]/spectracal.{{report_format}}"
      calmodels: "{{config_output}}/processed_{{fit_ne_peaks}}_{{match_mode}}_{{interpolator}}/[[key]]/calmodels"
      matched_peaks: "{{config_output}}/processed_{{fit_ne_peaks}}_{{match_mode}}_{{interpolator}}/[[key]]/matched_peaks.csv"
    upstream: "spectraframe_*"      
    params:
      config_templates: "{{config_templates}}"
      config_root: "{{config_root}}"
      neon_tag: "{{ne_tag}}"
      si_tag: "{{si_tag}}"
      pst_tag: "{{pst_tag}}"
      apap_tag: "{{apap_tag}}"
      calcite_tag: "{{calcite_tag}}"
      fit_neon_peaks: "{{fit_ne_peaks}}"
      match_mode: "{{match_mode}}"
      interpolator: "{{interpolator}}"   
      test_offset: 0
    grid:
      key: "{{calibration_key}}"



  - source: spectraframe_tips.py
    upstream: ["spectraframe_*"]
    name: "spectra_tips"   
    product: 
      nb: "{{config_output}}/twinning/spectraframe_tips.ipynb" 
 


  - source: spectraframe_ycalibrate.py
    name: "spectracaly_[[key]]"    
    product: 
      nb: "{{config_output}}/processed_{{fit_ne_peaks}}_{{match_mode}}_{{interpolator}}/[[key]]/spectracaly.{{report_format}}"
      ycalmodels: "{{config_output}}/processed_{{fit_ne_peaks}}_{{match_mode}}_{{interpolator}}/[[key]]/ycalmodels"      
    upstream: ["spectraframe_*","spectracal_*"]
    params:
      config_templates: "{{config_templates}}"
      config_root: "{{config_root}}"
      pst_tag: "{{pst_tag}}"
      apap_tag: "{{apap_tag}}"
    grid:
      key: "{{calibration_key}}"
      
 
  - source: calibration_verify.py
    upstream: ["spectraframe_*","spectracal_*","spectracaly_*"]
    name: "calibration_verify_[[mode]]"    
    product: 
      nb: "{{config_output}}/processed_{{fit_ne_peaks}}_{{match_mode}}_{{interpolator}}/assessment/calibration_verify_[[mode]].{{report_format}}"
      matched_peaks: "{{config_output}}/processed_{{fit_ne_peaks}}_{{match_mode}}_{{interpolator}}/assessment/matched_peaks_samples.csv"      
    params:
      config_templates: "{{config_templates}}"
      config_root: "{{config_root}}"
      validation_tag: "{{apap_tag}}"
      test_tags: "S0N"
      neon_tag: "{{ne_tag}}"
      si_tag: "{{si_tag}}"
      pst_tag: "{{pst_tag}}"
      calcite_tag: "{{calcite_tag}}"     
      match_mode: "{{match_mode}}"
      interpolator: "{{interpolator}}"      
    nbconvert_export_kwargs:
        # optionally hide the code from the report
        exclude_input: True            
    grid:
      mode: ["x", "xy"]


  - source: calibration_analysis.py
    upstream: ["spectracal_*", "calibration_verify_xy"]
    name: "calibration_analysis"    
    product: 
      nb: "{{config_output}}/processed_{{fit_ne_peaks}}_{{match_mode}}_{{interpolator}}/assessment/calibration_analysis_{{fit_ne_peaks}}_{{match_mode}}_{{interpolator}}.html"
      matched_peaks: "{{config_output}}/processed_{{fit_ne_peaks}}_{{match_mode}}_{{interpolator}}/assessment/matched_peaks_Ne.csv"
      analysis: "{{config_output}}/processed_{{fit_ne_peaks}}_{{match_mode}}_{{interpolator}}/assessment/analysis_{{fit_ne_peaks}}_{{match_mode}}_{{interpolator}}_Ne.png"
    params:
      exclude: "P6_0301"
      context: "Match mode {{match_mode}} Interpolators {{interpolator}} Fit Ne peaks {{fit_ne_peaks}}"
      sample_peaks: "C:\\Users\\jelia\\Nextcloud\\Projects\\VAMAS\\VAMAS_P6_analysis\\matched_peaks_samples-1.csv"
    nbconvert_export_kwargs:
        # optionally hide the code from the report
        exclude_input: True            


  - source: release.py
    upstream: ["calibration_verify_*"]
    product: 
      nb: "{{config_output}}/processed_{{fit_ne_peaks}}_{{match_mode}}_{{interpolator}}/assessment/release.html"
    params:
      results_folder: "{{config_output}}"
      release_folder: "{{release_folder}}"
      processed_folder: "processed_{{fit_ne_peaks}}_{{match_mode}}_{{interpolator}}"
      dataset_key: "{{dataset_key}}"      
      enable: "{{release_enable}}"
    nbconvert_export_kwargs:
        # optionally hide the code from the report
        exclude_input: True

  - source: qmatch.py
    name: "qmatch_[[key]]"    
    product: 
      nb: "{{config_output}}/processed_{{fit_ne_peaks}}_{{match_mode}}_{{interpolator}}/[[key]]/qmatch.html"
    upstream: "spectraframe_*"      
    params:
      config_templates: "{{config_templates}}"
      config_root: "{{config_root}}"
      neon_tag: "{{ne_tag}}"
      si_tag: "{{si_tag}}"
      pst_tag: "{{pst_tag}}"
      apap_tag: "{{apap_tag}}"
      calcite_tag: "{{calcite_tag}}"
      fit_neon_peaks: "{{fit_ne_peaks}}"
      match_mode: "{{match_mode}}"
      interpolator: "{{interpolator}}"   
      test_offset: 0
      mode: "qargmin2d" #None # None, "demo" "qargmin2d"
    grid:
      key: ["P6_0301", "P6_01201"]    
 